<h1 align="center">Applied Data Science Capstone</h1> 
<h3 align="center">Assignment 2</h3>
<h4 align="center">Segmenting and Clustering Neighborhoods in Toronto</h4>

In [1]:
# Import libraries
import pandas as pd
import requests
import lxml.html as lh

In [2]:
# URL to Wikipedia page
url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

page = requests.get(url)

#Store the page contents at the given URL
doc = lh.fromstring(page.content)

#Parse data between the row elements <tr> where the table class is 'wikitable'
data = doc.xpath('//table[@class="wikitable"]//tr')

In [3]:
len(data)

181

In [4]:
#Retrieve the headers from the first row 
table=[]
i=0

for t in data[0]:
    i+=1
    header=t.text_content()
    table.append((header,[]))
table

[('Postal code\n', []), ('Borough\n', []), ('Neighborhood\n', [])]

In [5]:
for i in range(1,len(data)):
    j=0
    for d in data[i]:
        table[j][1].append(d.text_content() )
        j+=1

In [6]:
df_dict={header:col for (header,col) in table}
df=pd.DataFrame(df_dict)
df.columns=['PostalCode','Borough','Neighborhood']
df

,PostalCode,Borough,Neighborhood
0,M1A\n,Not assigned\n,\n
1,M2A\n,Not assigned\n,\n
2,M3A\n,North York\n,Parkwoods\n
3,M4A\n,North York\n,Victoria Village\n
4,M5A\n,Downtown Toronto\n,Regent Park / Harbourfront\n
...,...,...,...
175,M5Z\n,Not assigned\n,\n
176,M6Z\n,Not assigned\n,\n
177,M7Z\n,Not assigned\n,\n
178,M8Z\n,Etobicoke\n,Mimico NW / The Queensway West / South of Bloo...
179,M9Z\n,Not assigned\n,\n

### Cleaning data

In [7]:
#Removing newline characters
df = df.replace('\n',' ', regex=True)
#Replace '/' with a ',' as required in the format
df = df.replace('/',',', regex=True)
df

,PostalCode,Borough,Neighborhood
0,M1A,Not assigned,
1,M2A,Not assigned,
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park , Harbourfront"
...,...,...,...
175,M5Z,Not assigned,
176,M6Z,Not assigned,
177,M7Z,Not assigned,
178,M8Z,Etobicoke,"Mimico NW , The Queensway West , South of Bloo..."
179,M9Z,Not assigned,

### Removing Rows where the Borough is 'Not assigned'

In [8]:
df = df[df.Borough!='Not assigned ']
df = df.reset_index(drop=True)
df

,PostalCode,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park , Harbourfront"
3,M6A,North York,"Lawrence Manor , Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park , Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway , Montgomery Road , Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,Business reply mail Processing CentrE
101,M8Y,Etobicoke,"Old Mill South , King's Mill Park , Sunnylea ,..."
102,M8Z,Etobicoke,"Mimico NW , The Queensway West , South of Bloo..."

In [9]:
df.shape

(103, 3)